version: '3.8'

services:
  publicator-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - publicator-db
    environment:
      - SERVER_PORT=24110
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://publicator-db:5432/distcomp
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "24110:24110"

  publicator-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=distcomp
    ports:
      - "5432:5432"

  cassandra-discussion-1:
    image: cassandra:latest
    environment:
        - CASSANDRA_SEEDS=cassandra-discussion-1 #,cassandra-discussion-2,cassandra-discussion-3
        - CASSANDRA_CLUSTER_NAME=discussions
        - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
        - CASSANDRA_USER=cassandra
        - CASSANDRA_PASSWORD_SEEDER=yes
        - CASSANDRA_PASSWORD=cassandra
    ports:
      - "9042:9042"

#  cassandra-discussion-2:
#    image: cassandra:latest
#    environment:
#      - CASSANDRA_SEEDS=cassandra-discussion-1,cassandra-discussion-2,cassandra-discussion-3
#      - CASSANDRA_CLUSTER_NAME=discussions
#      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
#      - CASSANDRA_USER=cassandra
#      - CASSANDRA_PASSWORD_SEEDER=yes
#      - CASSANDRA_PASSWORD=cassandra
#
#  cassandra-discussion-3:
#    image: cassandra:latest
#    environment:
#      - CASSANDRA_SEEDS=cassandra-discussion-1,cassandra-discussion-2,cassandra-discussion-3
#      - CASSANDRA_CLUSTER_NAME=discussions
#      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
#      - CASSANDRA_USER=cassandra
#      - CASSANDRA_PASSWORD_SEEDER=yes
#      - CASSANDRA_PASSWORD=cassandra