spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/distcomp
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: 'DC'
server:
  port: 24110
springdoc:
  api-docs:
    enabled: true
    path: /api/v1.0/docs
  swagger-ui:
    path: /api/v1.0/ui-docs.html