spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb # jdbc:postgresql:distcomp
    username: sa # postgres
    password: password # postgres
    driverClassName: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: 'DC'
server:
  port: 24110
springdoc:
  api-docs:
    enabled: true
    path: /api/v1/docs
  swagger-ui:
    path: /api/v1/ui-docs.html